const API='https://alt-cam-manager-bot.onrender.com',tokenKey='altcam-admin-token';
let token=sessionStorage.getItem(tokenKey)||'';
const $=s=>document.querySelector(s),headers=()=>({'Content-Type':'application/json','Authorization':`Bearer ${token}`}),money=n=>new Intl.NumberFormat('uk-UA').format(n||0)+' ₴',esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function api(path,options={}){const response=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});if(response.status===401){logout();throw new Error('unauthorized')}if(!response.ok)throw new Error(await response.text());return response.json()}
function logout(){token='';sessionStorage.removeItem(tokenKey);$('#app').hidden=true;$('#login').hidden=false;$('#logout').hidden=true}
async function start(){if(!token)return logout();try{await api('/api/admin/me');$('#login').hidden=true;$('#app').hidden=false;$('#logout').hidden=false;await dashboard()}catch{logout()}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));$('#login-status').textContent='Перевіряємо…';try{const result=await api('/api/admin/login',{method:'POST',body:JSON.stringify(data)});token=result.token;sessionStorage.setItem(tokenKey,token);$('#login-status').textContent='';await start()}catch{$('#login-status').textContent='Невірний email або пароль.'}});$('#logout').onclick=logout;
document.querySelectorAll('nav button').forEach(button=>button.onclick=async()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==button.dataset.view);if(button.dataset.view==='dashboard')await dashboard();if(button.dataset.view==='orders')await orders();if(button.dataset.view==='prices')await prices()});
async function dashboard(){const data=await api('/api/admin/dashboard');$('#metrics').innerHTML=[['Усі замовлення',data.orders],['Нові',data.new_orders],['Сума замовлень',money(data.revenue)],['Події за 30 днів',data.events_30d]].map(x=>`<article class="metric"><small>${esc(x[0])}</small><b>${esc(x[1])}</b></article>`).join('');$('#popular').innerHTML=data.popular.length?data.popular.map(x=>`<div class="popular-row"><code>${esc(x.product_id)}</code><b>${esc(x.views)}</b></div>`).join(''):'<p>Дані накопичуються.</p>'}
const statusLabels={new:'Новий',confirmed:'Підтверджений',awaiting_payment:'Очікує оплату',packing:'Комплектується',shipped:'Відправлений',completed:'Завершений',canceled:'Скасований'};
async function orders(){const filter=$('#order-filter').value,data=await api('/api/admin/orders'+(filter?`?status=${encodeURIComponent(filter)}`:''));$('#order-list').innerHTML=data.orders.length?data.orders.map(o=>`<article class="order" data-id="${Number(o.id)}"><div><h3>${esc(o.order_number)}</h3><small>${esc(new Date(o.created_at).toLocaleString('uk-UA'))}</small><p><b>${esc(o.customer.name)}</b> · ${esc(o.customer.phone)}<br>${esc(o.customer.email||'')}</p><p>${esc(o.delivery.label||o.delivery.type)}</p><div class="order-items">${o.items.map(i=>`${esc(i.name)} × ${Number(i.quantity)||1}`).join('<br>')}</div><strong>${esc(money(o.subtotal))}</strong></div><div><select class="status">${Object.entries(statusLabels).map(([v,l])=>`<option value="${v}" ${v===o.status?'selected':''}>${esc(l)}</option>`).join('')}</select><textarea class="note" placeholder="Коментар менеджера">${esc(o.manager_note||'')}</textarea><button class="save-order">Зберегти</button></div></article>`).join(''):'<p>Замовлень немає.</p>'}
$('#order-filter').onchange=orders;$('#order-list').addEventListener('click',async e=>{const button=e.target.closest('.save-order');if(!button)return;const card=button.closest('.order');button.disabled=true;try{await api(`/api/admin/orders/${card.dataset.id}`,{method:'PATCH',body:JSON.stringify({status:card.querySelector('.status').value,manager_note:card.querySelector('.note').value})});button.textContent='Збережено'}finally{setTimeout(()=>{button.disabled=false;button.textContent='Зберегти'},1200)}});
async function prices(){const data=await api('/api/admin/prices');$('#price-list').innerHTML=data.prices.map(p=>`<div class="price-row"><code>${esc(p.product_id)}</code><b>${esc(money(p.price))}</b><span>${p.enabled?'Активна':'Вимкнена'}</span></div>`).join('')||'<p>Індивідуальних цін ще немає.</p>'}
$('#price-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await api('/api/admin/prices',{method:'PUT',body:JSON.stringify({...data,enabled:true})});e.currentTarget.reset();await prices()});start();
