const API='https://alt-cam-crm-api.onrender.com',tokenKey='altcam-admin-token';
let token=sessionStorage.getItem(tokenKey)||'',currentUser=null;
const $=s=>document.querySelector(s),headers=()=>({'Content-Type':'application/json','Authorization':`Bearer ${token}`}),money=n=>new Intl.NumberFormat('uk-UA').format(n||0)+' ₴',esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function api(path,options={}){const response=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});if(response.status===401){logout();throw new Error('unauthorized')}if(!response.ok)throw new Error(await response.text());return response.json()}
function logout(){token='';sessionStorage.removeItem(tokenKey);$('#app').hidden=true;$('#login').hidden=false;$('#logout').hidden=true}
async function start(){if(!token)return logout();try{const me=await api('/api/admin/me');currentUser=me.user;document.querySelectorAll('.chief-only').forEach(x=>x.hidden=currentUser.role!=='chief');$('#login').hidden=true;$('#app').hidden=false;$('#logout').hidden=false;await dashboard()}catch{logout()}}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));$('#login-status').textContent='Перевіряємо…';try{const result=await api('/api/admin/login',{method:'POST',body:JSON.stringify(data)});token=result.token;sessionStorage.setItem(tokenKey,token);$('#login-status').textContent='';await start()}catch{$('#login-status').textContent='Невірний email або пароль.'}});$('#logout').onclick=logout;
document.querySelectorAll('nav button').forEach(button=>button.onclick=async()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('.view').forEach(x=>x.hidden=x.id!==button.dataset.view);if(button.dataset.view==='dashboard')await dashboard();if(button.dataset.view==='orders')await orders();if(button.dataset.view==='prices')await prices();if(button.dataset.view==='users')await users();if(button.dataset.view==='audit')await auditLog()});
async function dashboard(){const data=await api('/api/admin/dashboard');$('#metrics').innerHTML=[['Усі замовлення',data.orders],['Нові',data.new_orders],['Сума замовлень',money(data.revenue)],['Події за 30 днів',data.events_30d]].map(x=>`<article class="metric"><small>${esc(x[0])}</small><b>${esc(x[1])}</b></article>`).join('');$('#popular').innerHTML=data.popular.length?data.popular.map(x=>`<div class="popular-row"><code>${esc(x.product_id)}</code><b>${esc(x.views)}</b></div>`).join(''):'<p>Дані накопичуються.</p>'}
const statusLabels={new:'Нове',clarification:'Уточнення',ordered_from_supplier:'Замовлено у постачальника',waiting_tracking:'Очікуємо трек',shipped:'Відправлено',in_transit:'У дорозі',arrived:'Прибуло у відділення',received:'Отримано клієнтом',completed:'Завершено',problem:'Проблема',canceled:'Скасовано'};
const attentionStatuses=new Set(['new','arrived','problem']);
let orderSearchTimer=null,currentOrder=null;
const formatDate=value=>value?new Date(value).toLocaleString('uk-UA'):'—';
const statusOptions=value=>Object.entries(statusLabels).map(([key,label])=>`<option value="${key}" ${key===value?'selected':''}>${esc(label)}</option>`).join('');
$('#order-filter').innerHTML='<option value="">Усі статуси</option>'+statusOptions('');
function orderQuery(){const params=new URLSearchParams();const status=$('#order-filter').value,q=$('#order-search').value.trim();if(status)params.set('status',status);if(q)params.set('q',q);if($('#order-attention').checked)params.set('attention','1');return params.toString()}
function renderOrderCard(o){const customer=o.customer||{},delivery=o.delivery||{},items=o.items||[];return `<article class="order order-summary ${attentionStatuses.has(o.status)?'needs-attention':''}" data-id="${Number(o.id)}" tabindex="0"><div class="order-main"><div class="order-title"><div><h3>${esc(o.order_number)}</h3><small>${esc(formatDate(o.created_at))}</small></div><span class="status-badge status-${esc(o.status)}">${esc(statusLabels[o.status]||o.status)}</span></div><div class="order-customer"><b>${esc(customer.name||'Без імені')}</b><a href="tel:${esc(customer.phone||'')}">${esc(customer.phone||'Телефон не вказано')}</a><span>${esc(delivery.city||delivery.label||delivery.type||'Доставка не вказана')}</span></div><div class="order-items">${items.slice(0,3).map(i=>`${esc(i.name)} × ${Number(i.quantity)||1}`).join('<br>')}${items.length>3?`<small>+ ще ${items.length-3}</small>`:''}</div></div><div class="order-side"><strong>${esc(money(o.subtotal))}</strong>${o.tracking_number?`<code>${esc(o.tracking_number)}</code>`:'<small>Трек ще не додано</small>'}<button type="button" class="open-order">Відкрити картку</button></div></article>`}
async function orders(){const data=await api('/api/admin/orders'+(orderQuery()?`?${orderQuery()}`:''));const rows=Array.isArray(data.orders)?data.orders:[];const total=Number.isFinite(Number(data.total))?Number(data.total):rows.length;$('#order-list').innerHTML=rows.map(renderOrderCard).join('');$('#order-count').textContent=`Знайдено: ${total}`;$('#order-empty').hidden=rows.length>0}
async function openOrder(id){const data=await api(`/api/admin/orders/${id}`);currentOrder=data.order;const o=currentOrder,customer=o.customer||{},delivery=o.delivery||{},items=o.items||[],telegram=(o.telegram_username||'').replace(/^@/,'');$('#drawer-number').textContent=o.order_number;$('#order-details').innerHTML=`<section class="detail-section"><h3>Клієнт</h3><div class="detail-grid"><label>Ім’я<input value="${esc(customer.name||'')}" disabled></label><label>Телефон<input value="${esc(customer.phone||'')}" disabled></label><label>Місто<input value="${esc(delivery.city||delivery.label||'')}" disabled></label><label>Telegram<input name="telegram_username" value="${esc(telegram)}" placeholder="username без @"></label></div><div class="quick-actions">${telegram?`<a class="button-link" target="_blank" rel="noopener" href="https://t.me/${encodeURIComponent(telegram)}">Написати в Telegram</a>`:''}${o.drive_folder_url?`<a class="button-link secondary" target="_blank" rel="noopener" href="${esc(o.drive_folder_url)}">Відкрити папку Drive</a>`:''}</div></section><section class="detail-section"><h3>Склад замовлення</h3><div class="detail-items">${items.map(i=>`<div><span>${esc(i.name)}</span><b>${Number(i.quantity)||1} × ${esc(money(i.price))}</b></div>`).join('')}</div><strong class="detail-total">Разом: ${esc(money(o.subtotal))}</strong></section><section class="detail-section"><h3>Обробка</h3><div class="detail-grid"><label>Статус<select name="status">${statusOptions(o.status)}</select></label><label>Номер у постачальника<input name="supplier_order_number" value="${esc(o.supplier_order_number||'')}"></label><label>Служба доставки<select name="tracking_provider"><option value="">Не вибрано</option><option value="nova_poshta" ${o.tracking_provider==='nova_poshta'?'selected':''}>Нова Пошта</option><option value="ukrposhta" ${o.tracking_provider==='ukrposhta'?'selected':''}>Укрпошта</option><option value="other" ${o.tracking_provider==='other'?'selected':''}>Інша</option></select></label><label>Трек-номер<input name="tracking_number" value="${esc(o.tracking_number||'')}"></label><label class="wide">Посилання на папку Drive<input name="drive_folder_url" type="url" value="${esc(o.drive_folder_url||'')}" placeholder="https://drive.google.com/…"></label><label class="wide">Коментар менеджера<textarea name="manager_note">${esc(o.manager_note||'')}</textarea></label><label class="wide">Опис проблеми<textarea name="problem_note">${esc(o.problem_note||'')}</textarea></label></div></section><section class="detail-section"><h3>Історія змін</h3><div class="timeline">${renderHistory(o.status_history)}</div></section>`;$('#order-drawer').hidden=false;document.body.classList.add('drawer-open')}
function renderHistory(history=[]){if(!history.length)return '<p class="muted">Історія з’явиться після першої зміни.</p>';return [...history].reverse().map(entry=>`<div class="timeline-item"><small>${esc(formatDate(entry.at))} · ${esc(entry.admin_email||'система')}</small>${Object.entries(entry.changes||{}).map(([field,change])=>`<p><b>${esc(field==='status'?'Статус':field)}</b>: ${esc(field==='status'?(statusLabels[change.before]||change.before||'—'):(change.before||'—'))} → ${esc(field==='status'?(statusLabels[change.after]||change.after||'—'):(change.after||'—'))}</p>`).join('')}</div>`).join('')}
function closeOrder(){$('#order-drawer').hidden=true;document.body.classList.remove('drawer-open');currentOrder=null}
$('#order-list').addEventListener('click',e=>{const card=e.target.closest('.order-summary');if(card)openOrder(card.dataset.id)});$('#order-list').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.order-summary'))openOrder(e.target.closest('.order-summary').dataset.id)});document.querySelectorAll('[data-close-order]').forEach(element=>element.onclick=closeOrder);
$('#order-form').addEventListener('submit',async e=>{e.preventDefault();if(!currentOrder)return;const button=e.submitter,status=$('#order-save-status'),payload=Object.fromEntries(new FormData(e.currentTarget));button.disabled=true;status.textContent='Зберігаємо…';try{const data=await api(`/api/admin/orders/${currentOrder.id}`,{method:'PATCH',body:JSON.stringify(payload)});currentOrder=data.order;status.textContent='Збережено';await orders();await openOrder(currentOrder.id)}catch(error){status.textContent='Не вдалося зберегти'}finally{button.disabled=false;setTimeout(()=>status.textContent='',1800)}});
$('#order-filter').onchange=orders;$('#order-attention').onchange=orders;$('#order-search').oninput=()=>{clearTimeout(orderSearchTimer);orderSearchTimer=setTimeout(orders,350)};$('#order-reset').onclick=()=>{$('#order-search').value='';$('#order-filter').value='';$('#order-attention').checked=false;orders()};
async function prices(){const data=await api('/api/admin/prices');$('#price-list').innerHTML=data.prices.map(p=>`<div class="price-row"><code>${esc(p.product_id)}</code><b>${esc(money(p.price))}</b><span>${p.enabled?'Активна':'Вимкнена'}</span></div>`).join('')||'<p>Індивідуальних цін ще немає.</p>'}
$('#price-form').addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));await api('/api/admin/prices',{method:'PUT',body:JSON.stringify({...data,enabled:true})});e.currentTarget.reset();await prices()});start();
async function users(){const data=await api('/api/admin/users');$('#user-list').innerHTML=data.admins.map(user=>`<div class="user-row" data-id="${Number(user.id)}"><div><b>${esc(user.name)}</b><br><small>${esc(user.email)} · ${user.role==='chief'?'Головний адміністратор':'Адміністратор'}${user.last_login_at?' · вхід '+esc(new Date(user.last_login_at).toLocaleString('uk-UA')):''}</small></div><span>${user.active?'Активний':'Вимкнений'}</span>${user.role==='chief'?'<b>Захищено</b>':`<button class="toggle-user ${user.active?'danger':''}" data-active="${user.active?'false':'true'}">${user.active?'Вимкнути':'Увімкнути'}</button>`}</div>`).join('')}
$('#user-form').addEventListener('submit',async e=>{e.preventDefault();const status=$('#user-status'),data=Object.fromEntries(new FormData(e.currentTarget));status.textContent='Створюємо…';try{await api('/api/admin/users',{method:'POST',body:JSON.stringify(data)});e.currentTarget.reset();status.textContent='Адміністратора створено.';await users()}catch(error){status.textContent=String(error.message).includes('admin_limit')?'Досягнуто ліміт: головний адміністратор і три співробітники.':'Не вдалося створити адміністратора.'}});
$('#user-list').addEventListener('click',async e=>{const button=e.target.closest('.toggle-user');if(!button)return;await api(`/api/admin/users/${button.closest('.user-row').dataset.id}`,{method:'PATCH',body:JSON.stringify({active:button.dataset.active==='true'})});await users()});
const actionLabels={login:'Вхід',order_updated:'Зміна замовлення',price_updated:'Зміна ціни',admin_created:'Створення адміністратора',admin_updated:'Зміна адміністратора'};
async function auditLog(){const data=await api('/api/admin/audit');$('#audit-list').innerHTML=data.events.map(event=>`<div class="audit-row"><small>${esc(new Date(event.created_at).toLocaleString('uk-UA'))}<br>${esc(event.ip_address||'')}</small><div><b>${esc(actionLabels[event.action]||event.action)}</b><br><code>${esc(event.entity_type||'')} ${esc(event.entity_id||'')} ${esc(JSON.stringify(event.details||{}))}</code></div><span>${esc(event.admin_email)}</span></div>`).join('')||'<p>Журнал порожній.</p>'}
