const fallbackServices=[{id:'service-survey',title:'Обстеження та проєктування',description:'Зони контролю, кабельні траси, живлення та архів.',includes:['Консультація','Схема розміщення','Кошторис']}];
const services=Array.isArray(window.ALTCAM_SERVICES)?window.ALTCAM_SERVICES:fallbackServices;
const products=(Array.isArray(window.ALTCAM_CATALOG)?window.ALTCAM_CATALOG:[]).filter(item=>!/^(?:viatec|югторг|yugtorg|nadzor)$/i.test(item.brand||''));
const API='https://alt-cam-manager-bot.onrender.com';
const TELEGRAM='https://t.me/altcam_security_ua';
const sessionId=localStorage.getItem('altcam-session')||(crypto.randomUUID?crypto.randomUUID():String(Date.now()));
localStorage.setItem('altcam-session',sessionId);
let publicPrices={},cart=JSON.parse(localStorage.getItem('altcam-cart')||'[]'),visibleCount=48;
const $=selector=>document.querySelector(selector);
const grid=$('#product-grid'),search=$('#catalog-search'),category=$('#category-filter'),brand=$('#brand-filter'),sort=$('#sort-filter');
const resolution=$('#resolution-filter'),connection=$('#connection-filter'),placement=$('#placement-filter'),price=$('#price-filter'),loadMore=$('#load-more');
const clean=value=>String(value||'').replace(/<[^>]+>|&(?:nbsp|amp|quot|lt|gt);/gi,' ').replace(/\s+/g,' ').trim();
function inferFeatures(item){const text=clean(`${item.name} ${item.description}`),patterns=[/\b\d+(?:[.,]\d+)?\s*(?:Мп|MP)\b/ig,/\b(?:ІЧ|IR)\s*(?:до\s*)?\d+\s*м\b/ig,/\bIP\d{2}\b/ig,/\b(?:PoE|Wi[‑-]?Fi|HDCVI|HD[‑-]?TVI|AHD|ONVIF|ColorVu|AcuSense)\b/ig];return [...new Set(patterns.flatMap(pattern=>text.match(pattern)||[]))].slice(0,4);}
products.forEach(item=>{if(!Array.isArray(item.features)||!item.features.length)item.features=inferFeatures(item);});
const money=value=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(value)+' ₴';
const textOf=item=>clean([item.name,item.model,item.brand,item.description,...(item.features||[])].join(' ')).toLowerCase();
const unique=key=>[...new Set(products.map(item=>item[key]).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'uk'));
unique('category').forEach(value=>category.add(new Option(value,value)));
unique('brand').forEach(value=>brand.add(new Option(value,value)));
function track(event,data={}){fetch(API+'/api/analytics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,session_id:sessionId,page:location.pathname,data}),keepalive:true}).catch(()=>{});}
function defaultShowcase(list){const priority=['Комплекти відеоспостереження','Комплекти домофонії','Ajax та охоронна сигналізація','Системи контролю доступу','Кабель для систем безпеки'];return [...list].sort((a,b)=>{const ai=priority.indexOf(a.category),bi=priority.indexOf(b.category);return (ai<0?99:ai)-(bi<0?99:bi)||a.name.localeCompare(b.name,'uk')});}
function matchesAdvanced(item){const text=textOf(item),amount=Number(publicPrices[item.id]||item.price||0);if(resolution.value&&!new RegExp(`\\b${resolution.value}\\s*(мп|mp)\\b`,'i').test(text))return false;if(connection.value==='poe'&&!/\bpoe\b/i.test(text))return false;if(connection.value==='wifi'&&!/wi[‑-]?fi/i.test(text))return false;if(connection.value==='analog'&&!/(hdcvi|hdtvi|hd-tvi|ahd|аналог)/i.test(text))return false;if(placement.value==='outdoor'&&!/(вулич|зовніш|ip6[5-9]|outdoor)/i.test(text))return false;if(placement.value==='indoor'&&!/(внутріш|приміщ|indoor)/i.test(text))return false;if(price.value&&amount>Number(price.value))return false;return true;}
function productSchema(item,amount){return JSON.stringify({'@context':'https://schema.org','@type':'Product',name:clean(item.name),image:item.image,sku:item.sku||item.id,brand:{'@type':'Brand',name:item.brand==='ALT-CAM'?'Інший виробник':item.brand},offers:{'@type':'Offer',priceCurrency:'UAH',price:amount,availability:'https://schema.org/InStock',url:`${location.origin}${location.pathname}?product=${encodeURIComponent(item.id)}`}}).replace(/</g,'\\u003c');}
function renderProducts(){const query=search.value.trim().toLowerCase();let list=products.filter(item=>(!category.value||item.category===category.value)&&(!brand.value||item.brand===brand.value)&&(!query||textOf(item).includes(query))&&matchesAdvanced(item));if(sort.value==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'uk'));else if(sort.value==='price-asc')list.sort((a,b)=>(a.price||Infinity)-(b.price||Infinity));else if(sort.value==='price-desc')list.sort((a,b)=>(b.price||0)-(a.price||0));else if(sort.value==='featured'&&!category.value&&!brand.value&&!query)list=defaultShowcase(list);$('#result-count').textContent=`Знайдено: ${list.length}`;const visible=list.slice(0,visibleCount);grid.innerHTML=visible.length?visible.map(item=>{const amount=Number(publicPrices[item.id]||item.price||0),features=(item.features||[]).slice(0,4);return `<article class="product-card"><div class="product-image"><span class="stock">В наявності</span><img src="${item.image}" alt="${clean(item.name)}" loading="lazy" onerror="this.closest('.product-card').hidden=true"><span class="product-brand">ALT-CAM</span></div><div class="product-copy"><small>${clean(item.brand)}</small><h3>${clean(item.name)}</h3>${features.length?`<div class="product-features">${features.map(value=>`<span>${clean(value)}</span>`).join('')}</div>`:''}<p>${clean(item.description).slice(0,220)}</p><div class="price-orient"><strong>${amount?'від '+money(amount):'Ціна за запитом'}</strong><span class="availability">● В наявності</span></div><button class="price-button" data-consult="${item.id}">Отримати точну ціну</button><div class="product-bottom"><span>Гарантія та підбір ALT-CAM</span><button class="add-button" data-add="${item.id}">До кошика</button></div><script type="application/ld+json">${productSchema(item,amount)}</script></div></article>`;}).join(''):'<div class="no-results"><b>Нічого не знайдено.</b><br>Скиньте фільтри або напишіть інженеру — підберемо аналог.</div>';loadMore.hidden=visible.length>=list.length;}
function renderSolutions(){const definitions=[['solution-video','Відеоспостереження для будинку','4 камери, реєстратор, кабель і базове налаштування','Комплекти відеоспостереження'],['solution-ajax','Ajax для будинку','Hub, датчики руху й відкриття, налаштування застосунку','Ajax та охоронна сигналізація'],['solution-intercom','Домофонія та доступ','Монітор, виклична панель, замок і мобільний доступ','Комплекти домофонії']];$('#solutions-grid').innerHTML=definitions.map(([id,title,description,cat])=>{const sample=products.filter(x=>x.category===cat&&Number(x.price)>=5000).sort((a,b)=>(a.price||Infinity)-(b.price||Infinity))[0];return `<article class="solution-card"><span>ГОТОВЕ РІШЕННЯ</span><h3>${title}</h3><p>${description}</p><strong class="solution-price">${sample?.price?'обладнання від '+money(sample.price):'Персональний розрахунок'}</strong><button data-solution="${id}" data-title="${title}">Отримати точний розрахунок</button></article>`;}).join('');}
function renderServices(){$('#service-grid').innerHTML=services.map((item,index)=>`<article class="service-item"><span class="service-number">${String(index+1).padStart(2,'0')} · ${item.group||'Послуга'}</span><h3>${item.title}</h3><p>${item.description}</p><ul>${(item.includes||[]).map(value=>`<li>${value}</li>`).join('')}</ul>${item.priceFrom?`<strong>від ${money(item.priceFrom)} <small>${item.unit||''}</small></strong>`:''}<button data-service="${item.id}">Додати до заявки</button></article>`).join('');}
function saveCart(){localStorage.setItem('altcam-cart',JSON.stringify(cart));renderCart();}
function add(id,type='product',name=''){if(!cart.some(item=>item.id===id))cart.push({id,type,name});saveCart();track('add_to_cart',{id,type});}
function renderCart(){const rows=cart.map(entry=>{const item=entry.type==='service'?services.find(x=>x.id===entry.id):products.find(x=>x.id===entry.id);const name=item?.model||item?.title||item?.name||entry.name;return name?`<div class="cart-item"><div><b>${clean(name)}</b><br><small>${entry.type==='service'?'Послуга ALT-CAM':clean(item?.brand||'Готове рішення')}</small></div><button class="cart-remove" data-remove="${entry.id}">Видалити</button></div>`:'';}).join('');$('#cart-items').innerHTML=rows||'<div class="cart-empty">Кошик порожній.<br>Додайте обладнання або послугу.</div>';$('#cart-count').textContent=cart.length;}
function openCart(){$('#cart').classList.add('is-open');$('#cart').setAttribute('aria-hidden','false');}function closeCart(){$('#cart').classList.remove('is-open');$('#cart').setAttribute('aria-hidden','true');}
function reset(){[search,category,brand,sort,resolution,connection,placement,price].forEach(el=>el.value='');sort.value='featured';visibleCount=48;renderProducts();}
[search,category,brand,sort,resolution,connection,placement,price].forEach(el=>el.addEventListener(el===search?'input':'change',()=>{visibleCount=48;renderProducts();}));
$('#filter-reset').addEventListener('click',reset);document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{category.value=button.dataset.category;visibleCount=48;renderProducts();$('#products').scrollIntoView({behavior:'smooth'});}));loadMore.addEventListener('click',()=>{visibleCount+=48;renderProducts();});
grid.addEventListener('click',event=>{const consult=event.target.closest('[data-consult]');if(consult){const item=products.find(x=>x.id===consult.dataset.consult);add(item.id,'product');openCart();return;}const button=event.target.closest('[data-add]');if(button){add(button.dataset.add);openCart();}});
$('#solutions-grid').addEventListener('click',event=>{const button=event.target.closest('[data-solution]');if(button){add(button.dataset.solution,'solution',button.dataset.title);openCart();}});$('#service-grid').addEventListener('click',event=>{const button=event.target.closest('[data-service]');if(button){add(button.dataset.service,'service');openCart();}});$('#cart-items').addEventListener('click',event=>{const button=event.target.closest('[data-remove]');if(button){cart=cart.filter(x=>x.id!==button.dataset.remove);saveCart();}});$('#cart-open').addEventListener('click',openCart);$('#cart-close').addEventListener('click',closeCart);$('#cart-backdrop').addEventListener('click',closeCart);
$('#cart-order').addEventListener('click',async()=>{if(!cart.length)return;const name=$('#order-name').value.trim(),phone=$('#order-phone').value.trim(),city=$('#order-city').value.trim();if(!name||!phone){alert('Вкажіть ім’я та телефон.');return;}const items=cart.map(entry=>{const item=entry.type==='service'?services.find(x=>x.id===entry.id):products.find(x=>x.id===entry.id);return{id:entry.id,type:entry.type,name:item?.model||item?.title||item?.name||entry.name,price:publicPrices[entry.id]||item?.price||null};});let orderNumber='';try{const response=await fetch(API+'/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:{name,phone,city},items})});if(response.ok)orderNumber=(await response.json()).order_number||'';}catch{}const text=[`Вітаю! ${orderNumber?`Замовлення ${orderNumber}. `:''}Хочу отримати точну пропозицію:`,...items.map((item,index)=>`${index+1}. ${item.name}`),'',`Ім’я: ${name}`,`Телефон: ${phone}`,`Місто: ${city||'не вказано'}`].join('\n');window.open(`${TELEGRAM}?text=${encodeURIComponent(text)}`,'_blank','noopener');});
$('#consult-form').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget),status=$('#consult-status');status.textContent='Надсилаємо…';try{const response=await fetch(API+'/site-lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'catalog_consultation',source:location.href,client:{name:form.get('name'),phone:form.get('phone')},message:form.get('question')})});if(!response.ok)throw new Error();status.textContent='Дякуємо. Інженер зв’яжеться з вами.';event.currentTarget.reset();track('consultation_sent');}catch{status.innerHTML=`Не вдалося надіслати. <a href="${TELEGRAM}" target="_blank" rel="noopener">Напишіть у Telegram</a>.`;}});
async function loadPrices(){try{const response=await fetch(API+'/api/catalog/prices');if(response.ok)publicPrices=await response.json();}catch{}renderProducts();}
const requested=new URLSearchParams(location.search).get('product');if(requested&&products.some(item=>item.id===requested))search.value=requested;
renderSolutions();renderServices();renderCart();renderProducts();loadPrices();track('page_view');
