const fallbackServices=[{id:'service-survey',title:'Обстеження та проєктування',description:'Зони контролю, кабельні траси, живлення та архів.',includes:['Консультація','Схема розміщення','Кошторис']}];
const services=Array.isArray(window.ALTCAM_SERVICES)?window.ALTCAM_SERVICES:fallbackServices;
const allProducts=(Array.isArray(window.ALTCAM_CATALOG)?window.ALTCAM_CATALOG:[]).filter(item=>!/^(?:viatec|югторг|yugtorg|nadzor)$/i.test(item.brand||''));
const RECOMMENDED_PRODUCT_IDS=['viatec-6975','viatec-6973','viatec-6974','viatec-2979','viatec-5239','viatec-10624','viatec-11351','viatec-19095','viatec-10170','viatec-4169','viatec-12721','viatec-10255','viatec-12726','viatec-12725','viatec-15423','viatec-16787','viatec-11806','viatec-8110','viatec-11228','viatec-20734','viatec-2367','viatec-2371','viatec-2324','viatec-2369','viatec-2392','viatec-2330','viatec-2331','viatec-11735','viatec-18470','viatec-18474','viatec-21283','viatec-8447','viatec-4453','viatec-12718','viatec-9154','viatec-20816','viatec-17360','viatec-3742','viatec-7867','viatec-7868','viatec-18321','viatec-3055','viatec-1797','viatec-1742','viatec-1781','viatec-3990','viatec-1764','viatec-13636','viatec-13709','viatec-5166','viatec-7255','viatec-18496','viatec-19255','viatec-21187'];
const CATEGORY_LABELS=['Комплекти відеоспостереження','Камери відеоспостереження','Відеореєстратори та накопичувачі','Комплекти домофонії','Домофони та викличні панелі','Системи контролю доступу','Ajax та охоронна сигналізація','Альтернативна енергетика','Літієві акумулятори','Зарядні пристрої','Аксесуари для енергосистем','Акумулятори та елементи живлення','Аварійне електроживлення','Адаптери та блоки живлення','Мережеве обладнання','Кабельна продукція','Кронштейни та монтажні коробки','Аксесуари та витратні матеріали для монтажу','Електрика','Інструменти','Аксесуари для систем безпеки'];
const CATEGORY_GROUPS={video:['Комплекти відеоспостереження','Камери відеоспостереження','Відеореєстратори та накопичувачі'],ajax:['Ajax та охоронна сигналізація'],access:['Комплекти домофонії','Домофони та викличні панелі','Системи контролю доступу'],energy:['Альтернативна енергетика','Літієві акумулятори','Зарядні пристрої','Аксесуари для енергосистем','Акумулятори та елементи живлення','Аварійне електроживлення','Адаптери та блоки живлення'],network:['Мережеве обладнання'],electrical:['Електрика','Інструменти'],install:['Кабельна продукція','Кронштейни та монтажні коробки','Аксесуари та витратні матеріали для монтажу','Аксесуари для систем безпеки']};
const recommendedRank=new Map(RECOMMENDED_PRODUCT_IDS.map((id,index)=>[id,index]));
const rankedProducts=[...allProducts].sort((a,b)=>(recommendedRank.get(String(a.id))??99999)-(recommendedRank.get(String(b.id))??99999)||String(a.name).localeCompare(String(b.name),'uk'));
const identity=item=>String(item.sku||item.id||item.slug||`${item.brand}|${item.model||item.name}`).trim().toLowerCase();
const recommendedProducts=[];const seen=new Set();
for(const label of CATEGORY_LABELS){for(const item of rankedProducts.filter(product=>product.category===label).slice(0,5)){const key=identity(item);if(key&&!seen.has(key)){seen.add(key);recommendedProducts.push(item);}}}
for(const item of rankedProducts){if(recommendedProducts.length>=60)break;const key=identity(item);if(key&&!seen.has(key)){seen.add(key);recommendedProducts.push(item);}}
const products=recommendedProducts.slice(0,60);
function publicCategory(item){return CATEGORY_LABELS.includes(item.category)?item.category:'Аксесуари для систем безпеки';}
products.forEach((item,index)=>{item.publicCategory=publicCategory(item);item.recommendationOrder=index;});
const API='https://alt-cam-crm-api.onrender.com',TELEGRAM='https://t.me/altcam_security_ua';
const CONTACTS=window.ALTCAM_CONTACTS||{};
const catalogPhone=document.querySelector('.js-catalog-phone');
const catalogTelegram=document.querySelector('.js-catalog-telegram');
if(CONTACTS.phone){catalogPhone.hidden=false;catalogPhone.href=`tel:${CONTACTS.phone}`;catalogPhone.textContent=CONTACTS.phoneLabel||CONTACTS.phone;}
catalogTelegram.href=CONTACTS.telegram?`https://t.me/${CONTACTS.telegram}`:TELEGRAM;
catalogPhone?.addEventListener('click',()=>track('click_phone',{location:'catalog_header'}));
catalogTelegram?.addEventListener('click',()=>track('click_telegram',{location:'catalog_header'}));
const sessionId=localStorage.getItem('altcam-session')||(crypto.randomUUID?crypto.randomUUID():String(Date.now()));localStorage.setItem('altcam-session',sessionId);
let publicPrices={},cart=JSON.parse(localStorage.getItem('altcam-cart')||'[]'),visibleCount=12,activeGroup='';
const $=selector=>document.querySelector(selector),grid=$('#product-grid'),search=$('#catalog-search'),category=$('#category-filter'),brand=$('#brand-filter'),sort=$('#sort-filter'),resolution=$('#resolution-filter'),connection=$('#connection-filter'),placement=$('#placement-filter'),price=$('#price-filter'),loadMore=$('#load-more');
const entityDecoder=document.createElement('textarea');
const clean=value=>{entityDecoder.innerHTML=String(value||'');return entityDecoder.value.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();};
function inferFeatures(item){const text=clean(`${item.model||''} ${item.name} ${item.description}`),patterns=[/\b\d+(?:[.,]\d+)?\s*(?:Мп|MP)\b/ig,/\b(?:ІЧ|IR)\s*(?:до\s*)?\d+\s*м\b/ig,/\bIP\d{2}\b/ig,/\b(?:PoE|Wi[‑-]?Fi|HDCVI|HD[‑-]?TVI|AHD|ONVIF|ColorVu|AcuSense|Jeweller)\b/ig];return[...new Set(patterns.flatMap(pattern=>text.match(pattern)||[]))].slice(0,3);}
products.forEach(item=>{if(!Array.isArray(item.features)||!item.features.length)item.features=inferFeatures(item);});
const money=value=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(value)+' ₴';
const textOf=item=>clean([item.name,item.model,item.brand,item.description,...(item.features||[])].join(' ')).toLowerCase();
CATEGORY_LABELS.filter(value=>products.some(item=>item.publicCategory===value)).forEach(value=>category.add(new Option(value,value)));
[...new Set(products.map(item=>item.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'uk')).forEach(value=>brand.add(new Option(value,value)));
function track(event,data={}){fetch(API+'/api/analytics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,session_id:sessionId,page:location.pathname,data}),keepalive:true}).catch(()=>{});}
const viewedProducts=new Set();
const productObserver='IntersectionObserver' in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const id=entry.target.dataset.productId;if(id&&!viewedProducts.has(id)){viewedProducts.add(id);track('product_view',{id});}productObserver.unobserve(entry.target);}}),{threshold:.55}):null;
function observeProducts(){document.querySelectorAll('[data-product-id]').forEach(card=>{if(productObserver&&!viewedProducts.has(card.dataset.productId))productObserver.observe(card);});}
function matchesAdvanced(item){const text=textOf(item),amount=Number(publicPrices[item.id]||item.price||0);if(resolution.value&&!new RegExp(`\\b${resolution.value}\\s*(мп|mp)\\b`,'i').test(text))return false;if(connection.value==='poe'&&!/\bpoe\b/i.test(text))return false;if(connection.value==='wifi'&&!/wi[‑-]?fi/i.test(text))return false;if(connection.value==='analog'&&!/(hdcvi|hdtvi|hd-tvi|ahd|аналог)/i.test(text))return false;if(placement.value==='outdoor'&&!/(вулич|зовніш|ip6[5-9]|outdoor)/i.test(text))return false;if(placement.value==='indoor'&&!/(внутріш|приміщ|indoor)/i.test(text))return false;if(price.value&&(!amount||amount>Number(price.value)))return false;return true;}
function productSchema(item,amount){return JSON.stringify({'@context':'https://schema.org','@type':'Product',name:clean(`${item.name} ${item.model||''}`),image:item.image,sku:item.sku||item.id,brand:{'@type':'Brand',name:item.brand==='ALT-CAM'?'Інший виробник':item.brand},offers:{'@type':'Offer',priceCurrency:'UAH',price:amount||undefined,availability:availability(item).schema,url:`https://alt-cam.net.ua/catalog.html?product=${encodeURIComponent(item.id)}`}}).replace(/</g,'\\u003c');}
function productImages(item){return[...new Set([item.image,...(Array.isArray(item.images)?item.images:[])].map(clean).filter(Boolean))].slice(0,3);}
function productGallery(item,title,modal=false){const images=productImages(item);if(!images.length)return'<div class="product-placeholder"><span>▣</span>Фото незабаром</div>';const thumbs=images.length>1?`<div class="product-thumbs">${images.map((url,index)=>`<button type="button" data-gallery-image="${url}" aria-label="Фото ${index+1}" class="${index?'':'is-active'}"><img src="${url}" alt="" loading="lazy"></button>`).join('')}</div>`:'';return`<div class="${modal?'product-modal-gallery':'product-card-gallery'}"><img class="product-main-image" src="${images[0]}" alt="${title}" loading="lazy">${thumbs}</div>`;}
function shortDescription(item){const features=(item.features||[]).map(clean).filter(Boolean).slice(0,3);if(features.length)return features.join(' · ');const text=clean(item.description);return text.length>110?`${text.slice(0,107).replace(/\s+\S*$/,'')}…`:text||'Характеристики уточнюйте в інженера ALT-CAM.';}
function hoverFeatures(item){const values=[...(item.features||[])];if(values.length<4)values.push(...clean(item.description).split(/[;●.]/));return[...new Set(values.map(clean).filter(value=>value.length>2&&value.length<90))].slice(0,6);}
function availability(item){const raw=clean(item.availability||item.stock_status||item.status).toLowerCase();if(item.available===false||item.inStock===false||/(немає|відсут|out.of.stock)/i.test(raw))return{label:'Під замовлення',schema:'https://schema.org/PreOrder',className:'is-order'};return{label:'В наявності',schema:'https://schema.org/InStock',className:''};}
function productWord(count){const lastTwo=count%100,last=count%10;if(lastTwo>=11&&lastTwo<=14)return'товарів';if(last===1)return'товар';if(last>=2&&last<=4)return'товари';return'товарів';}
function renderProducts(){
  const query=search.value.trim().toLowerCase();
  let list=products.filter(item=>(!activeGroup||(CATEGORY_GROUPS[activeGroup]||[]).includes(item.publicCategory))&&(!category.value||item.publicCategory===category.value)&&(!brand.value||item.brand===brand.value)&&(!query||textOf(item).includes(query))&&matchesAdvanced(item));
  if(sort.value==='name')list.sort((a,b)=>clean(`${a.name} ${a.model||''}`).localeCompare(clean(`${b.name} ${b.model||''}`),'uk'));
  else if(sort.value==='price-asc')list.sort((a,b)=>(Number(publicPrices[a.id]||a.price)||Infinity)-(Number(publicPrices[b.id]||b.price)||Infinity));
  else if(sort.value==='price-desc')list.sort((a,b)=>(Number(publicPrices[b.id]||b.price)||0)-(Number(publicPrices[a.id]||a.price)||0));
  else list.sort((a,b)=>a.recommendationOrder-b.recommendationOrder);
  $('#result-count').textContent=`Знайдено: ${list.length} ${productWord(list.length)}`;
  const visible=list.slice(0,visibleCount);
  grid.innerHTML=visible.length?visible.map(item=>{
    const amount=Number(publicPrices[item.id]||item.price||0);
    const title=clean(`${item.name}${item.model?` ${item.model}`:''}`);
    const image=productGallery(item,title);
    const details=hoverFeatures(item),stock=availability(item),badges=(item.features||[]).map(clean).filter(Boolean).slice(0,4);
    const detailItems=(details.length?details:['Точні параметри підкаже інженер ALT-CAM']).map(value=>`<li>${value}</li>`).join('');
    return`<article class="product-card" tabindex="0" data-product-id="${clean(item.id)}"><div class="product-image">${image}</div><div class="product-copy"><span class="product-brand">${clean(item.brand||'ALT-CAM')}</span><h3 title="${title}">${title}</h3>${badges.length?`<div class="product-badges">${badges.map(value=>`<span>${value}</span>`).join('')}</div>`:''}<p class="product-summary">${shortDescription(item)}</p><strong class="product-price">${amount?'від '+money(amount):'Ціна за запитом'}</strong><span class="availability ${stock.className}">● ${stock.label}</span><span class="product-trust">✓ Підбір і гарантія ALT-CAM</span><div class="product-actions"><button class="price-button" data-consult="${item.id}">Отримати точну ціну</button><button class="add-button" data-add="${item.id}">У кошик</button></div><button class="product-more" data-details="${item.id}">Докладніше</button><script type="application/ld+json">${productSchema(item,amount)}</script></div><aside class="product-hover-panel"><b>Характеристики</b><ul>${detailItems}</ul><small>Перевіримо сумісність із вашою системою перед замовленням.</small></aside></article>`;
  }).join(''):'<div class="no-results"><b>Нічого не знайдено.</b><br>Скиньте фільтри або напишіть інженеру — підберемо аналог.</div>';
  loadMore.hidden=visible.length>=list.length;observeProducts();
}
const SOLUTIONS=[
{id:'solution-home-video',badge:'Популярне',title:'Відеоспостереження для приватного будинку — 4 камери',description:'Для будинку, двору, входу та периметра.',items:['4 камери','Реєстратор і HDD','Живлення та аксесуари','Налаштування доступу'],price:25290},
{id:'solution-business-video',badge:'Для бізнесу',title:'Відеоспостереження для магазину / офісу',description:'Контроль торгового залу, входу, касової зони або офісних приміщень.',items:['Камери','Реєстратор','Накопичувач','Базове обладнання'],price:28238},
{id:'solution-ajax',badge:'Під ключ',title:'Ajax охорона для квартири / будинку',description:'Захист від проникнення, відкриття дверей, руху та інших загроз.',items:['Hub Ajax','Датчики руху','Датчики відкриття','Сирена і застосунок'],price:14990},
{id:'solution-intercom',badge:'Готове рішення',title:'Відеодомофон + контроль доступу',description:'Відеодзвінок і дистанційне відкриття дверей або хвіртки.',items:['Відеодомофон','Виклична панель','Електрозамок','Блок живлення'],price:7184},
{id:'solution-ups',badge:'Робота без світла',title:'Система з резервним живленням UPS',description:'Відеоспостереження або охорона працюють під час відключення електроенергії.',items:['UPS','Акумулятор','Захист живлення','Розрахунок автономності'],price:3240},
{id:'solution-complete',badge:'Максимальний захист',title:'ALT-CAM Complete',description:'Комплексна система безпеки для будинку або бізнесу.',items:['Камери','Ajax','Домофон і доступ','Резервне живлення'],price:54900}
];
function renderSolutions(){$('#solutions-grid').innerHTML=SOLUTIONS.map(item=>`<article class="solution-card"><span class="solution-badge">${item.badge}</span><h3>${item.title}</h3><p>${item.description}</p><ul>${item.items.map(value=>`<li>${value}</li>`).join('')}</ul><strong class="solution-price">Обладнання від ${money(item.price)}</strong><button data-solution="${item.id}" data-title="${item.title}">Отримати точний розрахунок</button></article>`).join('');}
function renderServices(){$('#service-grid').innerHTML=services.map((item,index)=>`<article class="service-item"><span class="service-number">${String(index+1).padStart(2,'0')} · ${item.group||'Послуга'}</span><h3>${item.title}</h3><p>${item.description}</p><ul>${(item.includes||[]).map(value=>`<li>${value}</li>`).join('')}</ul>${item.priceFrom?`<strong>від ${money(item.priceFrom)} <small>${item.unit||''}</small></strong>`:''}<button data-service="${item.id}">Додати до заявки</button></article>`).join('');}
function saveCart(){localStorage.setItem('altcam-cart',JSON.stringify(cart));renderCart();}
function add(id,type='product',name=''){const existing=cart.find(item=>item.id===id&&item.type===type);if(existing)existing.quantity=(existing.quantity||1)+1;else cart.push({id,type,name,quantity:1});saveCart();track('add_to_cart',{id,type});}
function findCartItem(entry){return entry.type==='service'?services.find(x=>x.id===entry.id):allProducts.find(x=>String(x.id)===String(entry.id));}
function renderCart(){let total=0;const rows=cart.map(entry=>{const item=findCartItem(entry),name=item?.model||item?.title||item?.name||entry.name,quantity=entry.quantity||1,amount=Number(publicPrices[entry.id]||item?.price||item?.priceFrom||0);total+=amount*quantity;return name?`<div class="cart-item"><div><b>${clean(name)}</b><br><small>${entry.type==='service'?'Послуга ALT-CAM':clean(item?.brand||'Готове рішення')}</small>${amount?`<em>${money(amount)}</em>`:''}</div><div class="cart-controls"><button type="button" data-qty="-1" data-id="${entry.id}">−</button><b>${quantity}</b><button type="button" data-qty="1" data-id="${entry.id}">+</button><button type="button" class="cart-remove" data-remove="${entry.id}">×</button></div></div>`:'';}).join('');$('#cart-items').innerHTML=rows||'<div class="cart-empty">Кошик порожній.<br>Додайте обладнання або послугу.</div>';$('#cart-count').textContent=cart.reduce((sum,x)=>sum+(x.quantity||1),0);$('#cart-total').textContent=money(total);}
function openCart(){$('#cart').classList.add('is-open');$('#cart').setAttribute('aria-hidden','false');}function closeCart(){$('#cart').classList.remove('is-open');$('#cart').setAttribute('aria-hidden','true');}
function requestConsultation(item){const question=$('#consult-question');question.value=`Потрібна точна ціна: ${clean(item.name)} ${clean(item.model)}; ID: ${clean(item.sku||item.id)}; категорія: ${clean(item.publicCategory)}; орієнтир: ${Number(publicPrices[item.id]||item.price)?money(Number(publicPrices[item.id]||item.price)):'за запитом'}.`;$('#consultation').scrollIntoView({behavior:'smooth'});setTimeout(()=>question.focus(),450);track('price_request_started',{id:item.id});}
function openProduct(item){const amount=Number(publicPrices[item.id]||item.price||0),title=clean(`${item.name}${item.model?` ${item.model}`:''}`),stock=availability(item),features=hoverFeatures(item),image=productGallery(item,title,true);$('#product-modal-content').innerHTML=`<div class="product-modal-grid"><div class="product-modal-image">${image}</div><div><span class="product-brand">${clean(item.brand||'ALT-CAM')}</span><h2 id="product-modal-title">${title}</h2><span class="availability ${stock.className}">● ${stock.label}</span><strong class="product-modal-price">${amount?'від '+money(amount):'Ціна за запитом'}</strong><p>${clean(item.description)||shortDescription(item)}</p><h3>Характеристики</h3><ul>${(features.length?features:['Точні параметри підкаже інженер ALT-CAM']).map(value=>`<li>${value}</li>`).join('')}</ul><div class="product-modal-actions"><button data-modal-add="${item.id}">У кошик</button><button data-modal-consult="${item.id}">Потрібен монтаж / підбір</button></div></div></div>`;const modal=$('#product-modal');modal.hidden=false;modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');setTimeout(()=>modal.querySelector('.product-modal-close')?.focus(),0);track('product_details',{id:item.id});}
function closeProduct(){const modal=$('#product-modal');modal.hidden=true;modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}
function reset(){[search,category,brand,resolution,connection,placement,price].forEach(el=>el.value='');sort.value='featured';activeGroup='';document.querySelectorAll('[data-group]').forEach(button=>button.classList.toggle('is-active',button.dataset.group===''));visibleCount=12;renderProducts();}
[search,category,brand,sort,resolution,connection,placement,price].forEach(el=>el.addEventListener(el===search?'input':'change',()=>{visibleCount=12;renderProducts();}));
$('#filter-reset').addEventListener('click',reset);loadMore.addEventListener('click',()=>{visibleCount+=12;renderProducts();});
$('#category-chips').addEventListener('click',event=>{const button=event.target.closest('[data-group]');if(!button)return;activeGroup=button.dataset.group;document.querySelectorAll('[data-group]').forEach(item=>item.classList.toggle('is-active',item===button));category.value='';visibleCount=12;renderProducts();});
grid.addEventListener('error',event=>{if(event.target.tagName==='IMG')event.target.replaceWith(Object.assign(document.createElement('div'),{className:'product-placeholder',innerHTML:'<span>▣</span>Фото незабаром'}));},true);
function switchGalleryImage(button){const gallery=button.closest('.product-card-gallery,.product-modal-gallery'),main=gallery?.querySelector('.product-main-image');if(!main)return;main.src=button.dataset.galleryImage;gallery.querySelectorAll('[data-gallery-image]').forEach(item=>item.classList.toggle('is-active',item===button));}
grid.addEventListener('click',event=>{const gallery=event.target.closest('[data-gallery-image]');if(gallery){switchGalleryImage(gallery);return;}const consult=event.target.closest('[data-consult]');if(consult){const item=products.find(x=>String(x.id)===consult.dataset.consult);if(item)requestConsultation(item);return;}const button=event.target.closest('[data-add]');if(button){add(button.dataset.add);openCart();return;}const details=event.target.closest('[data-details]');if(details){const item=products.find(x=>String(x.id)===details.dataset.details);if(item)openProduct(item);}});
$('#product-modal').addEventListener('click',event=>{const gallery=event.target.closest('[data-gallery-image]');if(gallery){switchGalleryImage(gallery);return;}if(event.target.closest('[data-modal-close]')){closeProduct();return;}const addButton=event.target.closest('[data-modal-add]');if(addButton){add(addButton.dataset.modalAdd);closeProduct();openCart();return;}const consultButton=event.target.closest('[data-modal-consult]');if(consultButton){const item=products.find(x=>String(x.id)===consultButton.dataset.modalConsult);if(item){closeProduct();requestConsultation(item);}}});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#product-modal').hidden)closeProduct();});
$('#solutions-grid').addEventListener('click',event=>{const button=event.target.closest('[data-solution]');if(button){const question=$('#consult-question');question.value=`Потрібен точний розрахунок рішення «${button.dataset.title}».`;$('#consultation').scrollIntoView({behavior:'smooth'});setTimeout(()=>question.focus(),450);}});
$('#service-grid').addEventListener('click',event=>{const button=event.target.closest('[data-service]');if(button){add(button.dataset.service,'service');openCart();}});$('#cart-items').addEventListener('click',event=>{const remove=event.target.closest('[data-remove]');if(remove){cart=cart.filter(x=>x.id!==remove.dataset.remove);saveCart();return}const qty=event.target.closest('[data-qty]');if(qty){const entry=cart.find(x=>x.id===qty.dataset.id);if(entry){entry.quantity=Math.max(1,(entry.quantity||1)+Number(qty.dataset.qty));saveCart();}}});$('#cart-open').addEventListener('click',openCart);$('#cart-close').addEventListener('click',closeCart);$('#cart-backdrop').addEventListener('click',closeCart);
let selectedCity=null,selectedPlace=null,searchTimer;async function npSearch(kind,params){const response=await fetch(`${API}/api/nova-poshta/${kind}?${new URLSearchParams(params)}`);if(!response.ok)return[];const data=await response.json();return data.data||[]}
$('#delivery-city').addEventListener('input',event=>{clearTimeout(searchTimer);selectedCity=null;searchTimer=setTimeout(async()=>{const rows=await npSearch('cities',{q:event.target.value});$('#city-suggestions').innerHTML=rows.flatMap(group=>group.Addresses||[]).map(x=>`<button type="button" data-city-ref="${x.DeliveryCity||x.Ref}" data-city="${clean(x.Present)}">${clean(x.Present)}</button>`).join('')},350)});$('#city-suggestions').addEventListener('click',event=>{const button=event.target.closest('[data-city-ref]');if(!button)return;selectedCity={ref:button.dataset.cityRef,label:button.dataset.city};$('#delivery-city').value=selectedCity.label;$('#city-suggestions').innerHTML='';});
$('#delivery-place').addEventListener('input',event=>{clearTimeout(searchTimer);selectedPlace=null;searchTimer=setTimeout(async()=>{if(!selectedCity)return;const type=document.querySelector('[name=delivery]:checked').value;if(type==='courier')return;const rows=await npSearch('warehouses',{city_ref:selectedCity.ref,q:event.target.value});$('#place-suggestions').innerHTML=rows.filter(x=>type==='locker'?/поштомат/i.test(x.Description):!/поштомат/i.test(x.Description)).slice(0,30).map(x=>`<button type="button" data-place-ref="${x.Ref}" data-place="${clean(x.Description)}">${clean(x.Description)}</button>`).join('')},350)});$('#place-suggestions').addEventListener('click',event=>{const button=event.target.closest('[data-place-ref]');if(!button)return;selectedPlace={ref:button.dataset.placeRef,label:button.dataset.place};$('#delivery-place').value=selectedPlace.label;$('#place-suggestions').innerHTML='';});
document.querySelectorAll('[name=delivery]').forEach(input=>input.addEventListener('change',()=>{const type=document.querySelector('[name=delivery]:checked').value,place=$('#delivery-place');selectedPlace=null;place.value='';place.placeholder=type==='courier'?'Вулиця, будинок, квартира *':type==='locker'?'Оберіть поштомат *':'Оберіть відділення *';$('#delivery-fields').hidden=type==='pickup';}));
$('#checkout-form').addEventListener('submit',async event=>{event.preventDefault();if(!cart.length)return;const type=event.currentTarget.delivery.value,name=$('#order-name').value.trim(),phone=$('#order-phone').value.trim(),email=$('#order-email').value.trim(),city=$('#delivery-city').value.trim(),place=$('#delivery-place').value.trim(),status=$('#order-status'),needsInstallation=$('#needs-installation').checked;if(!name||!phone||(type!=='pickup'&&(!city||!place))){status.textContent='Заповніть контактні дані та адресу доставки.';return}const items=cart.map(entry=>{const item=findCartItem(entry);return{id:entry.id,type:entry.type,name:item?.model||item?.title||item?.name||entry.name,price:publicPrices[entry.id]||item?.price||item?.priceFrom||null,quantity:entry.quantity||1}}),labels={branch:'Нова пошта — відділення',locker:'Нова пошта — поштомат',courier:'Нова пошта — кур’єр',pickup:'Самовивіз: Вишгород, Кургузова 1А'},comment=$('#order-comment').value.trim(),orderComment=[comment,needsInstallation?'Потрібен монтаж / підбір.':''].filter(Boolean).join('\n');status.textContent='Оформлюємо…';try{const response=await fetch(API+'/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:{name,phone,email},delivery:{type,label:`${labels[type]}${type==='pickup'?'':`: ${city}, ${place}`}`,city,city_ref:selectedCity?.ref,place,place_ref:selectedPlace?.ref,comment:orderComment},needs_installation:needsInstallation,items})});if(!response.ok)throw new Error();const result=await response.json();status.textContent=`Замовлення ${result.order_number} прийнято. Менеджер зв’яжеться з вами.`;cart=[];saveCart();track('checkout_completed',{order_number:result.order_number,needs_installation:needsInstallation});}catch{status.innerHTML=`Не вдалося оформити. <a href="${TELEGRAM}" target="_blank" rel="noopener">Напишіть у Telegram</a>.`;}});
$('#consult-form').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget),status=$('#consult-status');status.textContent='Надсилаємо…';try{const response=await fetch(API+'/site-lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'catalog_consultation',source:location.href,client:{name:form.get('name'),phone:form.get('phone')},message:form.get('question')})});if(!response.ok)throw new Error();status.textContent='Дякуємо. Інженер зв’яжеться з вами.';event.currentTarget.reset();track('consultation_sent');}catch{status.innerHTML=`Не вдалося надіслати. <a href="${TELEGRAM}" target="_blank" rel="noopener">Напишіть у Telegram</a>.`;}});
async function loadPrices(){try{const response=await fetch(API+'/api/catalog/prices');if(response.ok)publicPrices=await response.json();}catch{}renderProducts();renderCart();}
const requested=new URLSearchParams(location.search).get('product');if(requested){const item=products.find(value=>String(value.id)===requested);if(item)search.value=item.model||item.name;}
renderSolutions();renderServices();renderCart();renderProducts();loadPrices();track('page_view');
