const fallbackServices=[{id:'service-survey',title:'Обстеження та проєктування',description:'Зони контролю, кабельні траси, живлення та архів.',includes:['Консультація','Схема розміщення','Кошторис']}];
const services=Array.isArray(window.ALTCAM_SERVICES)?window.ALTCAM_SERVICES:fallbackServices;
const allProducts=(Array.isArray(window.ALTCAM_CATALOG)?window.ALTCAM_CATALOG:[]).filter(item=>!/^(?:viatec|югторг|yugtorg|nadzor)$/i.test(item.brand||''));
const RECOMMENDED_PRODUCT_IDS=['viatec-6975','viatec-6973','viatec-6974','viatec-2979','viatec-5239','viatec-10624','viatec-11351','viatec-19095','viatec-10170','viatec-4169','viatec-12721','viatec-10255','viatec-12726','viatec-12725','viatec-15423','viatec-16787','viatec-11806','viatec-8110','viatec-11228','viatec-20734','viatec-2367','viatec-2371','viatec-2324','viatec-2369','viatec-2392','viatec-2330','viatec-2331','viatec-11735','viatec-18470','viatec-18474','viatec-21283','viatec-8447','viatec-4453','viatec-12718','viatec-9154','viatec-20816','viatec-17360','viatec-3742','viatec-7867','viatec-7868','viatec-18321','viatec-3055','viatec-1797','viatec-1742','viatec-1781','viatec-3990','viatec-1764','viatec-13636','viatec-13709','viatec-5166','viatec-7255','viatec-18496','viatec-19255','viatec-21187'];
const byId=new Map(allProducts.map(item=>[String(item.id),item]));
const identity=item=>String(item.sku||item.id||item.slug||`${item.brand}|${item.model||item.name}`).trim().toLowerCase();
const recommendedProducts=[];const seen=new Set();
for(const id of RECOMMENDED_PRODUCT_IDS){const item=byId.get(id),key=item&&identity(item);if(item&&key&&!seen.has(key)){seen.add(key);recommendedProducts.push(item);}}
const products=recommendedProducts.slice(0,60);
const CATEGORY_LABELS=['Відеоспостереження','Відеодомофони','Ajax та охоронні системи','Резервне живлення','Датчики, сирени та клавіатури','Кабель та аксесуари'];
function publicCategory(item){const c=item.category||'',t=`${item.name||''} ${item.model||''}`.toLowerCase();if(/кабель|кронштейн|коробк|монтажн|аксесуар/.test(c.toLowerCase()))return'Кабель та аксесуари';if(c==='Резервне живлення')return'Резервне живлення';if(/домоф|викличн/.test(c.toLowerCase()))return'Відеодомофони';if(c==='Ajax та охоронна сигналізація'&&/(датчик|сповіщувач|сирен|клавіатур|doorprotect|motionprotect|leaksprotect|glassprotect|fireprotect)/.test(t))return'Датчики, сирени та клавіатури';if(c==='Ajax та охоронна сигналізація'||c==='Системи контролю доступу'||c==='Аксесуари для систем безпеки')return'Ajax та охоронні системи';return'Відеоспостереження';}
products.forEach((item,index)=>{item.publicCategory=publicCategory(item);item.recommendationOrder=index;});
const API='https://alt-cam-manager-bot.onrender.com',TELEGRAM='https://t.me/altcam_security_ua';
const sessionId=localStorage.getItem('altcam-session')||(crypto.randomUUID?crypto.randomUUID():String(Date.now()));localStorage.setItem('altcam-session',sessionId);
let publicPrices={},cart=JSON.parse(localStorage.getItem('altcam-cart')||'[]'),visibleCount=12;
const $=selector=>document.querySelector(selector),grid=$('#product-grid'),search=$('#catalog-search'),category=$('#category-filter'),brand=$('#brand-filter'),sort=$('#sort-filter'),resolution=$('#resolution-filter'),connection=$('#connection-filter'),placement=$('#placement-filter'),price=$('#price-filter'),loadMore=$('#load-more');
const clean=value=>String(value||'').replace(/<[^>]+>|&(?:nbsp|amp|quot|lt|gt);/gi,' ').replace(/\s+/g,' ').trim();
function inferFeatures(item){const text=clean(`${item.model||''} ${item.name} ${item.description}`),patterns=[/\b\d+(?:[.,]\d+)?\s*(?:Мп|MP)\b/ig,/\b(?:ІЧ|IR)\s*(?:до\s*)?\d+\s*м\b/ig,/\bIP\d{2}\b/ig,/\b(?:PoE|Wi[‑-]?Fi|HDCVI|HD[‑-]?TVI|AHD|ONVIF|ColorVu|AcuSense|Jeweller)\b/ig];return[...new Set(patterns.flatMap(pattern=>text.match(pattern)||[]))].slice(0,3);}
products.forEach(item=>{if(!Array.isArray(item.features)||!item.features.length)item.features=inferFeatures(item);});
const money=value=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(value)+' ₴';
const textOf=item=>clean([item.name,item.model,item.brand,item.description,...(item.features||[])].join(' ')).toLowerCase();
CATEGORY_LABELS.forEach(value=>category.add(new Option(value,value)));
[...new Set(products.map(item=>item.brand).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'uk')).forEach(value=>brand.add(new Option(value,value)));
function track(event,data={}){fetch(API+'/api/analytics',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,session_id:sessionId,page:location.pathname,data}),keepalive:true}).catch(()=>{});}
function matchesAdvanced(item){const text=textOf(item),amount=Number(publicPrices[item.id]||item.price||0);if(resolution.value&&!new RegExp(`\\b${resolution.value}\\s*(мп|mp)\\b`,'i').test(text))return false;if(connection.value==='poe'&&!/\bpoe\b/i.test(text))return false;if(connection.value==='wifi'&&!/wi[‑-]?fi/i.test(text))return false;if(connection.value==='analog'&&!/(hdcvi|hdtvi|hd-tvi|ahd|аналог)/i.test(text))return false;if(placement.value==='outdoor'&&!/(вулич|зовніш|ip6[5-9]|outdoor)/i.test(text))return false;if(placement.value==='indoor'&&!/(внутріш|приміщ|indoor)/i.test(text))return false;if(price.value&&(!amount||amount>Number(price.value)))return false;return true;}
function productSchema(item,amount){return JSON.stringify({'@context':'https://schema.org','@type':'Product',name:clean(`${item.name} ${item.model||''}`),image:item.image,sku:item.sku||item.id,brand:{'@type':'Brand',name:item.brand==='ALT-CAM'?'Інший виробник':item.brand},offers:{'@type':'Offer',priceCurrency:'UAH',price:amount||undefined,availability:'https://schema.org/InStock',url:`${location.origin}${location.pathname}?product=${encodeURIComponent(item.id)}`}}).replace(/</g,'\\u003c');}
function shortDescription(item){const features=(item.features||[]).map(clean).filter(Boolean).slice(0,3);if(features.length)return features.join(' · ');const text=clean(item.description);return text.length>110?`${text.slice(0,107).replace(/\s+\S*$/,'')}…`:text||'Характеристики уточнюйте в інженера ALT-CAM.';}
function productWord(count){const lastTwo=count%100,last=count%10;if(lastTwo>=11&&lastTwo<=14)return'товарів';if(last===1)return'товар';if(last>=2&&last<=4)return'товари';return'товарів';}
function renderProducts(){const query=search.value.trim().toLowerCase();let list=products.filter(item=>(!category.value||item.publicCategory===category.value)&&(!brand.value||item.brand===brand.value)&&(!query||textOf(item).includes(query))&&matchesAdvanced(item));if(sort.value==='name')list.sort((a,b)=>clean(`${a.name} ${a.model||''}`).localeCompare(clean(`${b.name} ${b.model||''}`),'uk'));else if(sort.value==='price-asc')list.sort((a,b)=>(Number(publicPrices[a.id]||a.price)||Infinity)-(Number(publicPrices[b.id]||b.price)||Infinity));else if(sort.value==='price-desc')list.sort((a,b)=>(Number(publicPrices[b.id]||b.price)||0)-(Number(publicPrices[a.id]||a.price)||0));else list.sort((a,b)=>a.recommendationOrder-b.recommendationOrder);$('#result-count').textContent=`Знайдено: ${list.length} ${productWord(list.length)}`;const visible=list.slice(0,visibleCount);grid.innerHTML=visible.length?visible.map(item=>{const amount=Number(publicPrices[item.id]||item.price||0),title=clean(`${item.name}${item.model?` ${item.model}`:''}`),image=item.image?`<img src="${clean(item.image)}" alt="${title}" loading="lazy">`:'<div class="product-placeholder"><span>▣</span>Фото незабаром</div>';return`<article class="product-card"><div class="product-image">${image}</div><div class="product-copy"><h3 title="${title}">${title}</h3><p class="product-summary">${shortDescription(item)}</p><strong class="product-price">${amount?'від '+money(amount):'Ціна за запитом'}</strong><span class="availability">● В наявності</span><span class="product-trust">✓ Підбір і гарантія ALT-CAM</span><div class="product-actions"><button class="price-button" data-consult="${item.id}">Отримати точну ціну</button><button class="add-button" data-add="${item.id}">У кошик</button></div><script type="application/ld+json">${productSchema(item,amount)}</script></div></article>`;}).join(''):'<div class="no-results"><b>Нічого не знайдено.</b><br>Скиньте фільтри або напишіть інженеру — підберемо аналог.</div>';loadMore.hidden=visible.length>=list.length;}
const SOLUTIONS=[
{id:'solution-home-video',badge:'Популярне',title:'Відеоспостереження для приватного будинку — 4 камери',description:'Для будинку, двору, входу та периметра.',items:['4 камери','Реєстратор і HDD','Живлення та аксесуари','Налаштування доступу'],price:25290},
{id:'solution-business-video',badge:'Для бізнесу',title:'Відеоспостереження для магазину / офісу',description:'Контроль торгового залу, входу, касової зони або офісних приміщень.',items:['Камери','Реєстратор','Накопичувач','Базове обладнання'],price:28238},
{id:'solution-ajax',badge:'Під ключ',title:'Ajax охорона для квартири / будинку',description:'Захист від проникнення, відкриття дверей, руху та інших загроз.',items:['Hub Ajax','Датчики руху','Датчики відкриття','Сирена і застосунок'],price:14990},
{id:'solution-intercom',badge:'Готове рішення',title:'Відеодомофон + контроль доступу',description:'Відеодзвінок і дистанційне відкриття дверей або хвіртки.',items:['Відеодомофон','Виклична панель','Електрозамок','Блок живлення'],price:7184},
{id:'solution-ups',badge:'Робота без світла',title:'Система з резервним живленням UPS',description:'Відеоспостереження або охорона працюють під час відключення електроенергії.',items:['UPS','Акумулятор','Захист живлення','Розрахунок автономності'],price:3240},
{id:'solution-complete',badge:'Максимальний захист',title:'ALT-CAM Complete',description:'Комплексна система безпеки для будинку або бізнесу.',items:['Камери','Ajax','Домофон і доступ','Резервне живлення'],price:54900}
];
function renderSolutions(){$('#solutions-grid').innerHTML=SOLUTIONS.map(item=>`<article class="solution-card"><span class="solution-badge">${item.badge}</span><h3>${item.title}</h3><p>${item.description}</p><ul>${item.items.map(value=>`<li>${value}</li>`).join('')}</ul><strong class="solution-price">Обладнання від ${money(item.price)}</strong><button data-solution="${item.id}" data-title="${item.title}">Отримати точний розрахунок</button></article>`).join('');}
function renderServices(){$('#service-grid').innerHTML=services.map((item,index)=>`<article class="service-item"><span class="service-number">${String(index+1).padStart(2,'0')} · ${item.group||'Послуга'}</span><h3>${item.title}</h3><p>${item.description}</p><ul>${(item.includes||[]).map(value=>`<li>${value}</li>`).join('')}</ul>${item.priceFrom?`<strong>від ${money(item.priceFrom)} <small>${item.unit||''}</small></strong>`:''}<button data-service="${item.id}">Додати до заявки</button></article>`).join('');}
function saveCart(){localStorage.setItem('altcam-cart',JSON.stringify(cart));renderCart();}
function add(id,type='product',name=''){if(!cart.some(item=>item.id===id))cart.push({id,type,name});saveCart();track('add_to_cart',{id,type});}
function findCartItem(entry){return entry.type==='service'?services.find(x=>x.id===entry.id):allProducts.find(x=>String(x.id)===String(entry.id));}
function renderCart(){const rows=cart.map(entry=>{const item=findCartItem(entry),name=item?.model||item?.title||item?.name||entry.name;return name?`<div class="cart-item"><div><b>${clean(name)}</b><br><small>${entry.type==='service'?'Послуга ALT-CAM':clean(item?.brand||'Готове рішення')}</small></div><button class="cart-remove" data-remove="${entry.id}">Видалити</button></div>`:'';}).join('');$('#cart-items').innerHTML=rows||'<div class="cart-empty">Кошик порожній.<br>Додайте обладнання або послугу.</div>';$('#cart-count').textContent=cart.length;}
function openCart(){$('#cart').classList.add('is-open');$('#cart').setAttribute('aria-hidden','false');}function closeCart(){$('#cart').classList.remove('is-open');$('#cart').setAttribute('aria-hidden','true');}
function requestConsultation(item){const question=$('#consult-question');question.value=`Потрібна точна ціна: ${clean(item.name)} ${clean(item.model)}; ID: ${clean(item.sku||item.id)}; категорія: ${clean(item.publicCategory)}; орієнтир: ${Number(publicPrices[item.id]||item.price)?money(Number(publicPrices[item.id]||item.price)):'за запитом'}.`;$('#consultation').scrollIntoView({behavior:'smooth'});setTimeout(()=>question.focus(),450);track('price_request_started',{id:item.id});}
function reset(){[search,category,brand,resolution,connection,placement,price].forEach(el=>el.value='');sort.value='featured';visibleCount=12;renderProducts();}
[search,category,brand,sort,resolution,connection,placement,price].forEach(el=>el.addEventListener(el===search?'input':'change',()=>{visibleCount=12;renderProducts();}));
$('#filter-reset').addEventListener('click',reset);loadMore.addEventListener('click',()=>{visibleCount+=12;renderProducts();});
grid.addEventListener('error',event=>{if(event.target.tagName==='IMG')event.target.replaceWith(Object.assign(document.createElement('div'),{className:'product-placeholder',innerHTML:'<span>▣</span>Фото незабаром'}));},true);
grid.addEventListener('click',event=>{const consult=event.target.closest('[data-consult]');if(consult){const item=products.find(x=>String(x.id)===consult.dataset.consult);if(item)requestConsultation(item);return;}const button=event.target.closest('[data-add]');if(button){add(button.dataset.add);openCart();}});
$('#solutions-grid').addEventListener('click',event=>{const button=event.target.closest('[data-solution]');if(button){const question=$('#consult-question');question.value=`Потрібен точний розрахунок рішення «${button.dataset.title}».`;$('#consultation').scrollIntoView({behavior:'smooth'});setTimeout(()=>question.focus(),450);}});
$('#service-grid').addEventListener('click',event=>{const button=event.target.closest('[data-service]');if(button){add(button.dataset.service,'service');openCart();}});$('#cart-items').addEventListener('click',event=>{const button=event.target.closest('[data-remove]');if(button){cart=cart.filter(x=>x.id!==button.dataset.remove);saveCart();}});$('#cart-open').addEventListener('click',openCart);$('#cart-close').addEventListener('click',closeCart);$('#cart-backdrop').addEventListener('click',closeCart);
$('#cart-order').addEventListener('click',async()=>{if(!cart.length)return;const name=$('#order-name').value.trim(),phone=$('#order-phone').value.trim(),city=$('#order-city').value.trim();if(!name||!phone){alert('Вкажіть ім’я та телефон.');return;}const items=cart.map(entry=>{const item=findCartItem(entry);return{id:entry.id,type:entry.type,name:item?.model||item?.title||item?.name||entry.name,price:publicPrices[entry.id]||item?.price||null};});let orderNumber='';try{const response=await fetch(API+'/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:{name,phone,city},items})});if(response.ok)orderNumber=(await response.json()).order_number||'';}catch{}const text=[`Вітаю! ${orderNumber?`Замовлення ${orderNumber}. `:''}Хочу отримати точну пропозицію:`,...items.map((item,index)=>`${index+1}. ${item.name}`),'',`Ім’я: ${name}`,`Телефон: ${phone}`,`Місто: ${city||'не вказано'}`].join('\n');window.open(`${TELEGRAM}?text=${encodeURIComponent(text)}`,'_blank','noopener');});
$('#consult-form').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget),status=$('#consult-status');status.textContent='Надсилаємо…';try{const response=await fetch(API+'/site-lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'catalog_consultation',source:location.href,client:{name:form.get('name'),phone:form.get('phone')},message:form.get('question')})});if(!response.ok)throw new Error();status.textContent='Дякуємо. Інженер зв’яжеться з вами.';event.currentTarget.reset();track('consultation_sent');}catch{status.innerHTML=`Не вдалося надіслати. <a href="${TELEGRAM}" target="_blank" rel="noopener">Напишіть у Telegram</a>.`;}});
async function loadPrices(){try{const response=await fetch(API+'/api/catalog/prices');if(response.ok)publicPrices=await response.json();}catch{}renderProducts();}
const requested=new URLSearchParams(location.search).get('product');if(requested){const item=products.find(value=>String(value.id)===requested);if(item)search.value=item.model||item.name;}
renderSolutions();renderServices();renderCart();renderProducts();loadPrices();track('page_view');
