import {escape} from './landing-md.mjs';
export function priceTable(id,source,rates){
 const mappings={T1:['video.indoorCamera.one','video.indoorCamera.two','video.indoorCamera.threeToEight','video.indoorCamera.overEight','video.outdoorCamera.one','video.outdoorCamera.two','video.outdoorCamera.threeToEight','video.outdoorCamera.overEight','video.speedDomeMin','video.recorderSetup','video.mobileAppSetup','video.bracket','video.junctionBox','video.cableIndoorPerMeter','additional.cableBoxPerMeter',null],T2:['intercom.analogKit','intercom.analogMobileKit','intercom.ipKit','intercom.ipPanelSurface','intercom.ipMonitor','intercom.mobilePlace','additional.monitorInstall'],T3:['access.magneticLock','access.lockConnection','access.controller','access.reader','access.exitButtonSurface','access.backupPower','access.keyProgramming'],T4:['ajax.starterKit','ajax.hubSetup','ajax.motionIndoor','ajax.motionOutdoor','ajax.opening','ajax.leak','ajax.sirenIndoor','ajax.sirenOutdoor','ajax.keypad'],T5:['additional.routerSetup','additional.officeSetup','additional.remoteSetupMin','additional.serverCabinetAssembly','additional.powerSupply']};
 const section=source.split(new RegExp(`## ${id}\\.`))[1]?.split('\n## ')[0];if(!section||!mappings[id])throw Error(`Unknown table ${id}`);
 const rows=section.split('\n').filter(l=>l.startsWith('|')).slice(2).map(l=>l.split('|').slice(1,-1).map(x=>x.trim()));
 if(rows.length!==mappings[id].length)throw Error(`Price table mapping drift: ${id}`);
 const value=key=>key.split('.').reduce((o,k)=>o[k],rates);
 return `<div class="table-scroll" tabindex="0" role="region" aria-label="Ціни на роботи"><table><caption>Ціни за роботи, без обладнання та матеріалів; матеріали позначені окремо</caption><thead><tr><th scope="col">Робота / матеріал</th><th scope="col">Ціна</th></tr></thead><tbody>`+rows.map(([label,original],i)=>{const key=mappings[id][i];let price=key?original.replace(/\d[\d\s]*(?:–[\d\s]+)?(?= ₴)/,Number(value(key)).toLocaleString('uk-UA')):original;if(id==='T5'&&i===2)price=`${value(key)}–${rates.additional.remoteSetupMax} ₴`;return `<tr><td>${escape(label)}</td><td>${escape(price)}</td></tr>`;}).join('')+'</tbody></table></div><p class="table-hint">На вузькому екрані таблицю можна прокрутити горизонтально.</p>';
}
